on:
  push

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run:  echo "Commit message- ${{ github.event.head_commit.message }}"

      - name: Check if the commit message contains "conditions"
        id: check_message
        run:  |
          if [[ "${{ github.event.head_commit.message }}" == *"conditions"* ]]; then
            echo Condition matches
          else
            echo Condition does not match
          fi
