on:
  push

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
      - name: Check if the commit message contains "conditions"
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"conditions"* ]]; then
            echo "Condition does match."
            echo "::set-output name=check_success::true"
          else
            echo "Condition does not match."
            echo "::set-output name=check_success::false"
          fi
          
    outputs:
      run_tests: ${{ steps.set-output.outputs.check_success }}

  run-tests-success:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.check_success == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running success tests"
  
  run-tests-fail:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.check_success == 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running fail tests"
