on:
  push

jobs:
  job1-display_output:
    name: display a file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: job1-Display the output of the file
        run: |
          cat test.txt
        shell: bash

      - name: Output for job 2
        id: myoutput
        run: |
          echo "::set-output name=mystring::This is job1 output"
    
    outputs:
      job1_output: ${{ steps.myoutput.outputs.mystring }}

  job2-display_output:
    name: display the content
    runs-on: ubuntu-latest
    needs: job1-display_output        # for sequential jobs
    environment: course
    env:
      name: "Harry"
    steps:
      - name: job2-Display the content
        run: |
          echo "This name is $name"
          echo "The topic is ${{ vars.topic }}"
          echo "The password is ${{ secrets.password }}"
          echo "This is job2. The output is coming from job1 - ${{ needs.job1-display_output.outputs.job1_output }}"
        shell: bash

  call-reusable-workflow:
    uses: ./.github/workflows/reuseable-workflow.yaml
    with:
      message: "This is the main workflow."
